name: foodfridge_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.11.0' # Updated for better compatibility

dependencies:
  url_launcher: ^6.2.5
  flutter:
    sdk: flutter
  # All these must be indented by exactly 2 spaces
  flutter_fortune_wheel: ^1.2.0
  image_picker: ^1.0.4
  google_sign_in: ^6.3.0
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_ui_auth: ^3.0.1
  firebase_ui_oauth_google: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Standard for Dart 3+

flutter:
  uses-material-design: true
  assets:
    - assets/